.flowconfig
The default value for this is already false. https://flow.org/en/docs/config/options/#toc-experimental-const-params-boolean
=> Remove unnecessary flow config property

src/script.js
Change "Excected" -> "Expected" in the following error message
JIRA: https://engineering.paypalcorp.com/jira/browse/DTCHKINT-219
=> Fix misspelling in error message

package.json
Support for `data-uid` was added to belter@1.0.136 so we need sdk-client to be using at least that. 
https://github.com/krakenjs/belter/compare/v1.0.135...v1.0.136
I ran into this problem when updating a private server-side app to use the latest sdk-client.
=> Update belter to support data-uid

src/config.js
This is pretty minor, but the Dev Docs team thought it'd be a good idea. I don't see why not. "sb" might not be obvious to people right away. 
Added sandbox and test client-id aliases, then we'll update the https://developer.paypal.com/demo/checkout/#/pattern/client tool and other places it appears.
=> Added sandbox and test client-id aliases

server/constants.js, server/meta.jsx, test/server/meta.test.js
Current env is not set and smartcomponentnodeweb breaks if run with `NODE_ENV` set to local.  Also, local tunnel is not letting us keep our PayPal subdomain and so changing how we inspect the urls.
=> Fix local check

src/tracking.js
This PR updates the uid logging logic to account for apps that use the JS SDK and are hosted directly on www.paypal.com. 
- https://www.paypal.com/buttons/smart
- https://www.paypal.com/us/gifts/
=> Update uid logging to check xprops

src/script.js
This PR updates `getCSPNonce` to return an empty string by default. This will make it easier enforce the csp nonce values in paypal-checkout-components by making them required strings.
=> Update getCSPNonce to always return a string

server/constants.js, server/meta.jsx, test/server/meta.test.js
This PR adds support for loading checkout.js from the QA CDN.
For example, a test page should be able to leverage the QA CDN like so:
```html
<script src="https://uideploy--staticcontent--7482d416a81b5--ghe.preview.dev.paypalinc.com/api/checkout.js" data-paypal-checkout></script>
```
This PR adds support for trusting the `.paypalinc.com` domain when validating the url stored in sdkMeta that's used for second render.
=> Add support for using v4 from qa cdn

src/script.js, test/client/script.js
Sometimes when pulling locale from browser settings, we only receive a language without a country code. In cases where there is only one possible country match, we should be able to safely infer the correct country from the language provided.
- Check that there is only one possible country match for the provided language and use it for locale
- Add tests for `getLocale` to cover new code change and some existing cases
=> [DTCHKINT-244] Check for single country match from locale lang

server/constants.js, server/meta.jsx, test/server/meta.test.js
This PR updates the server-side host validation rules to support:
- https://www.paypal.cn/sdk/js?client-id=foo
- http://www.objects.paypal.cn/api/checkout.js
=> Update server-side validation to support for new .ca hosts

src/domains.js, test/client/config.js
The `env=sandbox_v2` functionality is no longer needed. We have been given the green light to delete it.
=> Remove unused sandbox_v2 logic

.eslintrc.js, src/declarations.js, src/domains.js, src/global.js, test/client/config.js, test/globals.js
This PR updates `getPayPalDomain()` and `getPayPalAPIDomain()` to be global build time variables. This logic moves from the client-side to the server-side for better geo support.
=> Move domain logic to the server-side

src/script.js, src/utils.js, test/client/script.js
- Special Language variants are now supported and are handled as new entire languages. Such strings contain no only the specific country language, but  the country as well, a detailed explanation [here](https://github.com/paypal/paypal-sdk-constants/pull/55) 
- https://github.com/paypal/paypal-sdk-constants/pull/55
- https://github.com/paypal/paypal-identity-components/pull/14
- https://github.com/paypal/paypal-checkout-components/pull/1637
- https://github.paypal.com/Checkout-R/clientsdknodeweb/pull/304
=> support for special country locales added

src/utils.js, test/client/script.js
Previously, any country that had `zh_Hant` as one of its available languages, the logic returned always `zh_Hant` as lang, ignoring variables as `en` or other supported languages. This fix solves that
- [Jira Ticket](https://engineering.paypalcorp.com/jira/browse/DTPPSDK-193)
- has to do with:  https://github.paypal.com/Checkout-R/clientsdknodeweb/pull/304
- https://github.paypal.com/Checkout-R/clientsdknodeweb/pull/306
- https://github.com/paypal/paypal-checkout-components/pull/1789
=> fix locales issue

server/meta.jsx, test/server/meta.test.js
This PR improves the `validateSDKUrl()` server-side logic with the following changes:
1. Ensures the protocol really starts with http or https. The Node url.parse() function seems to ignore certain prefixes. In the screenshot below, note how the original url string starts with `/uFEFF` but the parsed protocol  shows `https:`
2. Prevent backslashes and other potentially harmful characters from being included in the subdomain of the url.
=> Improve domain validation logic

server/meta.jsx, test/server/meta.test.js
This PR fixes an issue where the merchant-id validation logic was assuming every merchant-id value was an email. This only applies the email validation to values containing an `@` character.
=> Fix bug with merchant-id validation logic

test/client/global.js
The PR contains a new set of unit tests to increase the client(Karma) code coverage.
To avoid the failing CI check related to the client unit tests. Now is set to a minimum of 50% on the Codecov config. Previously we had a code coverage under the desire 50% of coverage and CI check fails for all the PRs.
The name of the test cases probably aren't accurate, any feedback on that is welcome.
=> Increase the test coverage on the client to avoid failing checks in the CI

test/client/api.js, test/client/index.js
The PR increases the unit test coverage in the script file for the client(karma). Also, split the scripts test file in two to avoid fat files in the repo.
Take a look at this code: https://github.com/paypal/paypal-sdk-client/blob/52b7f85e19e3c80c65907aecd17f715496e3b0ac/src/api.js#L105 there we check if the `merchantID` is valid, but we get the `merchantID` from the function `getMerchantID`. That specific function returns an empty array if a merchant wasn't passed in the query parameters, meaning the check `![]` always be false in JS, meaning at the end we don't care if the `merchantID` is an empty array or not and we aren't able to throw the exception for the case user define a payee but a merchant id wasn't register corerctly.
=> Increase unit test coverage in the api file 🧪 

.eslintrc.js, .flowconfig, babel.config.js, karma.conf.js, package.json, src/declarations.js, webpack.config.js
[DTPPSDK-941](https://engineering.paypalcorp.com/jira/browse/DTPPSDK-941)
* Migrated to grumbler scripts v8.  
* Added `flow-typed`, `jest`, and `cross-env` as explicit dev-dependencies.  
* Added declaration for `__WEB__` to resolve flow errors.
=> feat: upgrade to grumbler-scripts 8

.eslintrc.js, src/declarations.js, src/global.js, src/logger.js, src/types.js, test/client/global.js, test/globals.js
Got
```
__EXPERIMENTATION__: {
__EXPERIENCE__: "1234, 4321";
__TREATMENT__: "8765,7890";
}
```
from global, then inside getExperimentation(), format it and return
```
experimation:{
experience: "1234, 4321",
treatment: "8765,7890"
}
```
=> [DTPPSDK-1319]Add getExperimentation()

server/meta.jsx, src/experiment.js, src/tracking.js, test/server/meta.test.js
Decode SDK meta if the meta is passed as URL encoded value.
=> Decode the sdk meta if url encoded meta is passed

.github/workflows/publish.yml, publish.sh
Update publish script for alpha versions
=> update publish script to publish alpha versions

src/tracking.js
* changing the gauge to actually be a gauge
* added new dimensions
* added a new init count metric and included a bunch more dimensions there too
* misc cleanup
=> new metrics and dimensions for sdk init

src/logger.js, src/tracking.js
* use the new `metricCounter` interface
* move one of the metrics outside of an if statement that doesn't apply to the metric
* add base metric namespace for ppcp and the dimensions for v5 web.
* add deprecated comment to `sendMetricCount`
=> use new metric helpers

src/dpop.js, src/dpop.test.js, test/globals.js
This PR implements a few utility functions that will be used in an upcoming PR for jwt creation and signatures as part of the larger [DPoP](https://datatracker.ietf.org/doc/html/rfc9449) initiative that will be used in the hosted buttons component. 
I am planning on two follow up prs to this repo:
- one that implements the key pair generation and signing and verification
- one that implements the jwt creation and exports a `dPoPHeaders` function that will be used in checkout-components.
=> add DPoP encoding utils

src/dpop.js, src/dpop.test.js
This PR is a follow-up to https://github.com/paypal/paypal-sdk-client/pull/184 and implements key pair generation and a `jsonWebKeyThumbprint` function that serializes and hashes a JSON web key.
The next (last) PR will implement the JWT creation and signature.
=> add DPoP keygen and thumbprint

src/dpop.js, src/dpop.test.js, src/index.js
This PR is a follow-up PR to https://github.com/paypal/paypal-sdk-client/pull/186 and is the last of the DPoP related changes in sdk-client.
This PR implements the JWT creation and signature and exports a single method to consumers of this package, `buildDPoPHeaders`, that abstracts away all of the lower-level cryptographic and encoding related functionality.
=> add DPoP createJWT and buildDPoPHeaders function

src/dpop.test.js
This PR fixes an issue where `crypto.subtle.verify` expects a byte array for the signature instead of a string. see https://github.com/paypal/paypal-sdk-client/actions/runs/8009694187/job/21878949911#step:7:204
After this PR is merged, I would like to submit another PR to update the node version in main.yml:
https://github.com/paypal/paypal-sdk-client/blob/639b4d5312db22dc4127cb25b41b8ebae73e8b5b/.github/workflows/main.yml#L17-L19
because it differs from the publish action's node version: 
https://github.com/paypal/paypal-sdk-client/blob/639b4d5312db22dc4127cb25b41b8ebae73e8b5b/.nvmrc#L1
https://github.com/paypal/paypal-sdk-client/blob/639b4d5312db22dc4127cb25b41b8ebae73e8b5b/.github/workflows/publish.yml#L11-L18
=> Fix node 18 type error

.github/workflows/main.yml
This PR fixes an issue where pull requests are tested using node 16 but npm publish actions are tested using node 18.
I copied over the yaml from `publish.yml`:
https://github.com/paypal/paypal-sdk-client/blob/4b87e823d890abbc7187dfa0800277e237427a59/.github/workflows/publish.yml#L14-L18
=> use node version from .nvmrc in ci

src/dpop.js, src/dpop.test.js
This PR uses the `RS256` signing and verification algorithm instead of `ES256`. This change was requested by the identity team who will be using `RS256` for the signature verification.
[example jwt](https://jwt.io/#debugger-io?token=eyJhbGciOiJSUzI1NiIsInR5cCI6ImRwb3Arand0IiwiandrIjp7ImtleV9vcHMiOlsidmVyaWZ5Il0sImV4dCI6dHJ1ZSwia3R5IjoiUlNBIiwibiI6Imx4Wnc3WkpXcDl1WFJ0UTlvNmQycGVFelJBN1pBLWtRbU9DRjg5TFNJb2JfYXh1Y0RaZUhBeWxfaXFKZlMtNDlncWNMZzJDUGdjd083Rk9WLXRLeFp2Ty1pdkE2X09Hcm9DQ1hwaFlRU2ZzOW1jWGhCbkRBcjBXRkRjRk1Rc3laNzdYX3dHdkJPWVV2YnpNU1dLazAxR1g2WHQ1VlJyOVFyREdZZlRiSDVsVEdmMjhjZlZ3QXRNMUx4WnUtcURQenZTWW5vNzlNZ2NsY0ZWVTlUZ1pOd2JMeHJPeDlWdjJtLVNfM3FDRFk2aHRXbHJIQmtNeUF0eUJ3YWJGR2l4YkpCUGwxOWdtZnlIUjI2RnlCaXJ1ZmZVVFJBLWxXdE1WNURGNGtSLUhVblhYWjBSaXd4MnhGeGF4SkpGOUJRRnhNZXRWMmVTWml0endlek55Z01 …
=> DPoP: use RS256 instead of ES256

package.json, src/script.js, src/script.test.js, src/tracking.js
Herein lies part of the effort charged by DTPPCPSDK-1482.
This sends `jsSdkLibrary` to FPTI & SFX for 1st and 2nd render.
=> Log JS SDK library

src/tracking.js, src/tracking.test.js
The `isLoadedInFrame` variable previously was `isPayPalDomain() && window.xprops`. Because of the && operator, the value here would be the value of window.xprops which is a very high cardinality value. We ended up having metrics disabled due to the cardinality of these events so casting to a Boolean should solve for that.
One thing I'm not clear on is why we're mapping `isLoadedInFrame` to `isPayPalDomain` and not calling `isPayPalDomain()` directly, but I'm only trying to solve the cardinality issue on this event.
=> Fix for incorrect metric causing high cardinality

src/script.test.js, src/tracking.js
@gregjopa, @westeezy, and I had a solid chat about DTPPCPSDK-1482 where it was decided we'd remove `JS_SDK_LIBRARIES` from `@paypal/sdk-constants` and hardcode values. This was inspired by the difficulty of adding `@paypal/sdk-constants` as a dependency of `paypal-js`. Additionally, it was decided that `"none"` was a better value than `"raw-script"` for when a library isn't being used to load the JS SDK.
=> Hardcode library values

package.json, src/script.js, src/script.test.js
This PR is an initial entrance to allow the latest vault flow (ID token) to work the new SDK token. It will not enable the e2e flow just yet.
When SDK token is passed alone, internally we will set the ID token as the SDK token value. We also will use this new getCustomerId function that decodes the SDK token for UX improvements to prevent an API call/correct loading state.
=> Add initial entry point for vault flows with SDK token

src/script.js
Review this commit: [b161d3f](https://github.com/paypal/paypal-sdk-client/commit/b161d3f1912354716245bfe6ee50cb44c3620136)
The first commit changes `SDK_SETTINGS` to `SDK_DATA_ATTRIBUTES`
=> Shopper session

package.json
This should have been part of https://github.com/paypal/paypal-sdk-client/pull/196, since this now relies on the new constant added in https://github.com/paypal/paypal-sdk-constants/pull/149.
=> Updated the @paypal/sdk-constants dependency version.

src/domains.test.js
The test case written to validate invalid Venmo domains are currently asserting for invalid domain by not passing protocol (http/https) in the input values.
This results in `www.venmo.com` being validated as invalid Venmo domain, and `https://www.venmo.com` being valid domain. 
A crucial part of invalid domain validation must be to also validate the eTLD+1 of the Venmo domain. 
This PR fixes by adding the protocol to the input values.
=> fix invalid venmo domain tests

src/setup.js
[DTPPCPSDK-2163](https://paypal.atlassian.net/browse/DTPPCPSDK-2163)
=> feat: add compatibility with window alias strategy

src/global.js, src/types.js
Flow was complaining about the typing of the inexactness of getFirstRenderExperiments so I made it more exact.
=> Update getFirstRenderExperiments types

src/session.js, src/session.test.js
**JIRA:** [DTPPCPSDK-2369](https://paypal.atlassian.net/browse/DTPPCPSDK-2369)
- _**💥 Adds wasShopperInsightsUsed function**_ - Checks session state for key indicators that shopper insights was used
=> Add wasShopperInsightsUsed 👾

server/meta.jsx, server/meta.test.js
This PR adds support for the new `payment-flow` query parameter for the web-sdk bridge url.
=> Add support for 'payment-flow' query param for the web-sdk bridge

server/meta.jsx, server/meta.test.js
This PR adds support for the optional `debug` query parameter for the web-sdk bridge url.
=> Add support for 'debug' query param for the web-sdk bridge

server/meta.integration.test.js, server/meta.jsx, server/meta.test.js
This PR updates the web-sdk query param validation logic so that `payment-flow` is considered an optional parameter.
=> Update 'payment-flow' param for web-sdk bridge to be optional

package.json
[flow-remove-types](https://www.npmjs.com/package/flow-remove-types?activeTab=readme) was recently updated which seems to have broken our `npm run release` task (ex: https://github.com/paypal/paypal-sdk-client/actions/runs/11463927109/job/31898934970). This PR should fix the following flow error:
```
Error -------------------------------------------- node_modules/hermes-parser/dist/traverse/getVisitorKeys.js.flow:18:50
Unexpected identifier, expected the token `{`
18| export function isNode(thing: mixed) /*: implies thing is {+[string]: mixed} */ {
```
=> fix: pin to version of flow-remove-types

src/domains.js, src/domains.test.js
- Support a new method `isPayPalTrustedUrl()` which validates if the provided URL is PayPal or Venmo URL. 
- Using the standard URL object instead of `getActualDomain` for future compatibility https://github.com/krakenjs/cross-domain-utils/blob/8f7bb2d9e07c465a5c625724b980f1f551dd28fa/src/utils.js#L91
=> feat: support new method to validate url

src/globalSession.js, src/globalSession.test.js, src/index.js
Retrieve `globalSessionID` value from a new session created by Messaging components when more than a namespace are being used at the same time. Besides retrieving it, we should log the data on tracking button events on a prop named `global_session_id`
Here's the step by step to check if this change is working, but both changes on `paypal-sdk-client`, `smartcomponentnodeweb`, `paypal-sdk-constants` and `paypal-checkout-components` are needed
- Open your site, network tab and wait for logger requests
- Wait for any button event like `process_button_load`
- Check if `global_session_id` property exists. IT SHOULDN'T
- After it, go to console, copy and paste this:
```
window.localStorage.__paypal_global_5_0_500_storage__ = JSON.stringify({
globalSessionID: "uid_testID",
})
```
- Reload the …
=> Adding globalSession to maintain the global_paypal storage
