package.json
src/logger.js
src/script.js
test/client/logger.js
test/client/script.js

sdk integration source script parameter to track sources of smart  buttons integrations
Screenshot of network tab:

feat: add sdk integration source script parameter

---

src/graphql.js
src/script.js

Waiting for corresponding changes in eligibility service to merge before merging this pr.

[DO NOT MERGE]Added enable funding

---

package.json
server/constants.js
server/meta.jsx
src/domains.js
test/server/meta.test.js

This allows for local testing of changes on native devices.

Allow local testing

---

package.json
src/script.js

Add `getUserExperienceFlow` function to support CCO changes for pay with nonce.
Requires change to constants [PR #48](https://github.com/paypal/paypal-sdk-constants/pull/48)

Add getUserExperienceFlow

---

src/index.js

Export utils

---

src/utils.js

Small improvement over an existing function

function improvemnt

---

server/meta.jsx
test/server/meta.test.js

Related Draft PR: https://github.com/paypal/paypal-sdk-client/pull/86
Related ticket: https://engineering.paypalcorp.com/jira/browse/DTPPSDK-424

(DTPPSDK-424) better merchant-id email validation

---

.github/codecov.yml
.github/workflows/main.yml
package.json

Change the names of the flags karma by `client` and jest by `server`.
To clarify the meaning of the flags and make it understandable for the external viewer.

Enhance the codecov report

---

server/meta.jsx
test/server/meta.test.js

The PR covert all the missing  Jest tests in the `meta.jsx` file.
To have a full coverage on the server (Jest) unit test

Increase jest test to 100% of coverage

---

test/server/meta.integration.test.js

Create a unit test case with real data information from the logs to make sure the `unpackSDKMeta` is working as expected.
To test the `unpackSDKMeta` with real information from merchants' use cases.

Test the unpackSDKMeta with real data

---

test/client/index.js
test/client/session.js

The PR increases the unit test coverage in the session.js file for the client(karma).

Increase unit test coverage on session file

---

test/client/domains.js

The PR increases the unit test coverage in the domain.js file for the client(karma).

Increase unit test coverage on domains file

---

src/script.js
test/client/index.js
test/client/script.js
test/client/scriptUtils.js

The PR increases the unit test coverage in the script file for the client(karma). Also, split the scripts test file in two to avoid fat files in the repo.
Not able to increase the coverage to 100%, there are some missing specific paths to tests.

Increase unit test coverage in the scripts file 🧪 

---

src/graphql.js
test/client/graphql.js
test/client/index.js

The PR increases the unit test coverage in the graphql file for the client(karma).

Increase unit test coverage in the graphql file 🧪 

---

src/domains.js
test/client/domains.js

fix(venmo): domain regex

---

src/logger.js

move loggerUrl inside getLogger function

[DTPPSDK-1252]fix '__PAYPAL_DOMAIN__ is not defined' error

---

server/meta.jsx
server/meta.test.js

This adds support for validating and loading the NextGen SDK bridge, which is used to communicate back to a merchant page running the NextGen SDK.
**Note:** This depends on https://github.com/paypal/paypal-sdk-constants/pull/149

Added support for validating and loading the web-sdk bridge.

---

server/meta.jsx
server/meta.test.js

This updates the validation for the NextGen SDK bridge URL. The merchant `origin` is no longer being passed as a parameter on the Checkout URL, but will be included in the `sdkMeta` as a parameter on the bridge URL. The bridge URL will also include a `version` parameter.

Updated validation of the web-sdk bridge URL.

---

package.json

add -- so bable-node parses webpack flags correctly

Update babel-node script

---

src/globalSession.js
src/paypalSession.js
src/paypalSession.test.js

Add new methods to create session ids on the using __paypal__storage__ as the localStorage key

add new methods to get paypal session id
